sudo: required
language: generic
services:
  - docker

branches:
  only:
    - feature

before_install:
  - docker build -t ndjerrou/docker-react-travis .

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: frontend
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-399231255960'
  on:
    branch: feature
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
