sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ndjerrou/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true ndjerrou/docker-react-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: frontend
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-399231255960'
  on:
    branch: trunk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
